title: ROBOTICS LAB URJC
email: lopezmuniciodiego@gmail.com
description: "Weekly blog of my TFG"
url: "https://roboticslaburjc.github.io"
baseurl: "/2025-tfg-diego-lopez"
github_username: dlopezm17
logo: ./logo.png
search: true

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown

permalink: /blog/:title/

paginate: 5
paginate_path: /page:num/

timezone: Europe/Madrid

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

author:
  name: "Diego López Municio"
  bio: "Ingeniería Robótica Software en la Universidad Rey Juan Carlos"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dlopezm17"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dlopezm17"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true